r-lib/devtools

- NEWS.md
- R/build.r
- R/check.r
- R/release.r
- man/build.Rd
- man/check.Rd
* `build()` gains an additional argument `manual`, defaults to `FALSE`.
* `check()` gains an ellipsis `...` which is passed unmodified to `build()`.
Completely untested, submitted for review. Will report once it's tested.
Fixes #603.
> `release()` now builds packages without the `--no-manual` switch, both for checking and for actually building the release package

- R/load-dll.r
- R/remove-s4-class.r
`devtools:::assignNativeRoutines()` "assumed" the 'methods' is attached.  Fix is obvious.  Discovered it by the from running the following(*):
```r
res <- devtools::load_all(".", export_all=FALSE, quiet=FALSE, recompile=TRUE)
...
Error in assignNativeRoutines(dlls[[lib]], lib, env, nsInfo$nativeRoutines[[lib]
]) :
could not find function "getPackageName"
```
Footnote:
(*) Actually from running `covr::package_coverage()`, but the above is basically the first thing it does.
> getPackageName -> methods::getPackageName

- NEWS.md
- R/install-github.r
- tests/testthat/test-github.r
Installing a pull request now uses the repository associated with the pull request's branch (and not the repository of the user who created the pull request).
Example: A shared repository where a collaborator has issued a pull request within this shared repo, e.g., `devtools::install_github("johnmyleswhite/ProjectTemplate#134")`
Includes a test.
> Use correct repository when using install_github with a pull request

- R/load-data.r
- man/load_data.Rd
According to the R-extension manual data-files should have the extension
.RData and not .Rdata
(http://cran.r-project.org/doc/manuals/R-exts.html#Data-in-packages).
Consistent with that, load_data() only loads .RData files (at least on
windows), but no .Rdata files. I only changed the documentation to be
consistent with that, i.e., specifically refer to .RData files.
> Documentation of load_data() to .RData, not .Rdata

- NEWS.md
- R/compile-dll.r
`compile_dll()` currently fails when package is being built in `tempdir()`
I'm not sure how common this use case is, but the fix is simple enough.  The reproducible example seems contrived but I have a workflow that is basically doing this.
To trigger: try to build a package that needs compilation in the directory given by `tempdir()`, even as a subdirectory.  As `devtools:::install_min` works in `tempdir()` too, the preclean causes the entire package to be removed.
Undesirable behaviour:
```r
path <- tempdir()
file.copy(system.file("tests/testthat/testDllRcpp", package="devtools"),
path, recursive=TRUE)
pkg <- file.path(path, "testDllRcpp")
dir(pkg) # package ready to be built/etc.
devtools::load_all(pkg) # or devtools::document(), etc
#
```
The directory is now empty:
```
dir(pkg)
```
I …
> Allow compile_dll to work when source is in tempdir()

- NEWS.md
- R/R.r
- man/install_version.Rd
- man/r_env_vars.Rd
Currently devtools always sets `NOT_CRAN`. In some cases, it's desirable to override this behaviour (e.g. to check the behaviour on CRAN). This patch simply checks whether `NOT_CRAN` has been set externally and if so, doesn't change it.
> Allow to override NOT_CRAN

- .travis.yml
This modifies the old config to use the native R support.
Note that the old config was careful about ordering of installation in order to ensure that we were using the cloned devtools. I've been more naive about that, but IIUC we're still testing the right thing: https://travis-ci.org/craigcitro/devtools/builds/52301857
If I'm missing something, maybe the right thing to do is to just run a manual `remove.packages` in the `before_script`?
> Update .travis.yml for native R support.

- inst/templates/travis.yml
It seems to be, this evening.
In the world's weakest pull request, I have added 'sudo: required' to the travis.yml template.
> travis.yml - sudo: required (#749)

- DESCRIPTION
- NEWS.md
- R/lint.r
- man/lint.Rd
Combined with the bugfix in 2fbfee237c39c47cda15e93e96ef74a16b4bc40d this allows use of the caching functionality in lintr.
Reference timings (lints were previously cached)
```r
system.time(devtools::lint('../../../devtools', cache = FALSE))
#> Linting devtools.....................................................................................................................................
#>    user  system elapsed
#>  85.842   0.660  86.692
system.time(devtools::lint('../../../devtools', cache = TRUE))
#> Linting devtools.....................................................................................................................................
#>    user  system elapsed
#>   3.990   0.139   4.187
> Add default cache argument for lint

- README.md
SVG looks better on Retina displays. Verified improvement in the latest versions of Safari, Chrome & Firefox on a mid-2012 Retina MacBook Pro running OS X Mavericks.
> Use SVG instead of PNG for Travis badge

- R/build-github-devtools.r
An attempt to address https://github.com/hadley/devtools/issues/761 (edit: turns out my devtools was out of date, but the `unzip` utility is gone from devtools so this should be necessary regardless)
> fix unzip ambiguity

- NEWS.md
- R/install.r
- man/install.Rd
- man/install_deps.Rd
This allows you to pass all arguments to `install.packages` if needed.
Motivation for this is to be able to set a alternate repo argument for `install_deps`, for instance to use `devtools::install()` to automatically install dependencies for a bioconductor package.
```r
install(repos = BiocInstaller::biocinstallRepos(), dependencies = TRUE)
```
> Add argument to `install()` and `install_deps()`

- NEWS.md
- R/install-github.r
- R/utils.r
- man/install_github.Rd
- tests/testthat/test-github.r
Add warning when downloading from github repo that uses submodules 
(assessed through presence of .gitsubmodules file). 
Help for install_github updated to suggest use of install_git with proper args in this case.
Limited testing (with mock responses from download and attempt to download .gitsubmodules).
Partially responsive to #737
> Fix/install GitHub submodule warn

- R/infrastructure.R
The function `use_test()` used the wrong path and would overwrite the test file.
> Wrong path

- R/infrastructure.R
When using the functions `use_test()`, `use_package_doc()` and `use_revdep()` from outside the project root, files were overwritten.
Also fix small typo.
> Use full path when checking if file exists

- NEWS.md
- R/check.r
- tests/testthat/test-check.r
Is active only with `check(cran = TRUE, check_version = TRUE)`. Emits a warning if no spell checker is found (checked via `utils::aspell(NULL)` because the worker function `utils:::aspell_find_program` is not exported).
R source reference: https://github.com/wch/r-source/blob/deb67e31fd0106dae7ab0d274ab874e56ab1b7b5/src/library/tools/R/QC.R#L6517
> spell-check package description

- R/infrastructure.R
@gaborcsardi noted that gh repo name might not always match package name. This small change should fix that.
> Minor update to use_cran_badge

- R/load.r
Otherwise, it's impossible to create/setup a package in a subdirectory of an existing package.
(Sorry for the other bogus pull request.)
> Don't use package root for create_description

- NEWS.md
- R/vignettes.r
- man/build_vignettes.Rd
- tests/testthat/test-vignettes.r
Passed to `install_deps()`.
Use case: run `build_vignettes(dependencies = FALSE)` in tests
> build_vignettes() gains dependencies argument

- .travis.yml
Example for failing test: https://travis-ci.org/krlmlr/devtools/builds/64078115#L1608
> install up-to-date lintr from GitHub

- NEWS.md
- R/infrastructure.R
- R/load.r
- tests/testthat/test-infrastructure.r
- tests/testthat/test-load-dir.r
- tests/testthat/test-load.r
- tests/testthat/test-package.R
- tests/testthat/testUseData/DESCRIPTION
- tests/testthat/testUseData/NAMESPACE
Includes test for overall functionality and for this particular feature.
Closes #816 (=includes it).
> use_data also works with data from the parent frame

- CONDUCT.md
The link to [contributor-covenant.org](http://contributor-covenant.org/) had no forward slashes and so doesn't show up as a link on GitHub.
> Add forward slashes to Contributor Covenant URL in CONDUCT.md

- R/rtools.r
First search for the key in HKCU before attempting HKLM in case the user installed Rtools while on a non-admin account.
> Improve rtools registry path detection

- NEWS.md
- R/load.r
- R/package.r
- man/as.package.Rd
- man/load_all.Rd
- tests/testthat/test-load.r
Governs if a package structure should be created if it is missing. If `NA`, the user is queried (in interactive mode only).
This also changes the semantics of `load_all()`: Now, a package is created only if no `DESCRIPTION` is found in the directory hierarchy, and only if requested or approved by the user. Any `DESCRIPTION` in a parent directoy will be used if found.
All relevant code paths tested.
Fixes #852.
> as.package and load_all gain new argument 'create'

- tests/testthat/test-check.r
- tests/testthat/testTest/DESCRIPTION
Caused by too restrictive tests. Passes the previously failing test on win-builder now:
- R-devel: http://win-builder.r-project.org/B43aMx2dhNzO/
- R-stable: http://win-builder.r-project.org/Dgi7yJvgEZww/
Follow-up to #798.
> Fix regressions on win-builder

- tests/testthat/test-check.r
- tests/testthat/test-test.r
- silent test of test() function
- skip problematic test of check() on CRAN
> Prepare for CRAN release

- NEWS.md
- R/with.r
- tests/testthat/test-with.r
- Reset library path after `with_lib()`
- Includes test that fails without this modification
Closes #833, I'm planning to implement the `with_temp_lib()` function largely from scratch.
> with_lib resets library path

- NEWS.md
- R/deps.R
- R/utils.r
If the user specified repositories take precedence over the default
Bioconductor repositories.
This allows one to use `install_github()` with Bioconductor packages and have the dependencies work like any other package. e.g.
```r
install_github("Bioconductor-mirror/S4Vectors")
```
> Use BiocInstaller repositories if installing a Bioconductor package

- tests/testthat/test-with.r
Something was weird with the normalization of the paths, perhaps some 8.3 problem. Now the tests also normalize the return value of .libPaths(), this seems to fix the issue.
Works according to WinBuilder:
http://win-builder.r-project.org/4NAgZD9sPrem.
~~~This should now work also on Windows, if not please ping me again.~~~
> Fix with_lib tests on Windows

- .gitignore
- DESCRIPTION
- NEWS.md
- R/deps.R
- R/release.r
- R/utils.r
- tests/testthat/test-remotes.r
- vignettes/dependencies.Rmd
This allows package authors to specify DevPackage in their DESCRIPTION,
which devtools will use to install development versions of the
dependencies prior to looking for them in normal repositories.  The
format is 'type|user/repo', where type is optional (default github)
defining the install_type to use, e.g. (git, gitorious, svn, ect.).
An example description would be (for the ggplot2 book for instance)
```
Package: ggbook2
Title: ggbook2 is not really an R package, but this is here to list the dependencies for building the ggplot2 book.
Version: 0.1
Authors@R: person("First", "Last", email = "first.last@example.com",
role = c("aut", "cre"))
Depends: R (>= 3.1.0)
URL: https://github.com/hadley/ggplot2-book
Imports:
lubridate,
rvest,
magrittr,
dplyr,
plyr,
tidyr,
xtable,
nlme,
effects, …
```
> DevPackage Dependencies

- NEWS.md
- R/remove-s4-class.r
- tests/testthat/test-s4-sort.r
- tests/testthat/test-s4-unload.r
- tests/testthat/testS4sort/DESCRIPTION
- tests/testthat/testS4sort/NAMESPACE
- tests/testthat/testS4sort/R/classes.r
prevents derived classes to remain orphan
Fixes #848
> remove_s4_classes() respecting inheritance

- R/deps.R
The last refactoring of `install_dev_remotes` had a bug which made it non-functional.
This should fix things so it actually works, sorry I missed this earlier!
> bugfix when calling install_dev_remotes

- R/infrastructure-git.R
- man/use_github.Rd
Solves difficulties setting remote tracking branch when protocol is ssh and the ssh keys have a passphrase. See https://github.com/hadley/devtools/issues/642.
> Allow for ssh keys with passphrase

- NEWS.md
- R/imports-env.r
in `process_imports`
Reason: Otherwise, `devtools::document` cannot fix a `NAMESPACE` file that became invalid due to changes in external packages
(I'm not sure if this worked before.)
> convert errors to warnings when processing NAMESPACE

- R/release.r
It was missing a newline
```
Error: Can't find cran-comments.md in withr.
This file gives CRAN volunteers comments about the submission,
and it must exist.  Please create it using this guide:
http://r-pkgs.had.co.nz/release.html#release-checkThen run use_build_ignore('cran-comments.md')
```
> Fix error message in release()

- NEWS.md
- R/deps.R
The previous implementation used `match.fun()`, which has the undesirable effect that the function cannot be found if the devtools namespace is not attached.
So `devtools::install_deps()` would fail, which is what was happening on travis (https://travis-ci.org/hadley/devtools/builds/81765159#L2108-L2110) when I tried to use `Remotes:`
This fix uses `get()` directly in the `devtools` namespace, so works regardless if devtools is attached.
> Use get directly instead of match.fun

- inst/templates/readme-rmd-pre-commit.sh
* do nothing if neither README.Rmd nor README.md staged
* keep checking that .md is newer than .Rmd
* check that both are staged
* tell user how to override
> Modify pre-commit hook re: README.Rmd; fixes #979

- NEWS.md
- R/install.r
- R/load.r
- R/unload.r
This is a workaround for a bug in base R. unloadNamespace does not
unregister any S3 methods, so the promises are invalid if you install a
new version of a package, try to unload and re-load the package.
See https://stat.ethz.ch/pipermail/r-devel/2015-December/072150.html for
more details and a reproducible example.
This fixes the common lazy-load errors people often run into when trying
to use devtools' install functions.
Fixes #419, #503, #942, #631
> Unregister S3 methods explicitly

- NEWS.md
- R/revdep.R
Depending on if the user has ran BiocInstaller::useDevel() the
repository URL differs. The previous behavior was hard-coded to look only
at Bioconductor package in the last release. Making URL a parameter
ensures that if the user changes from looking at devel to release in the
same session the previous cached result will not be used.
> Use the proper Bioconductor URL for both release and devel

- DESCRIPTION
- NEWS.md
- R/check-cran.r
- R/deps.R
- R/doctor.R
- R/document.r
- R/infrastructure.R
- R/lint.r
- R/load.r
- R/missing-s3.r
- R/rcpp-attributes.r
- R/revdep-summarise.R
- R/run-example.r
- R/test.r
- R/upload-ftp.r
- R/utils.r
- man/package_deps.Rd
This allows devtools to be installed in less time, such as when it is
used only to install packages and dependencies on Travis and other CIs.
If a given Suggested dependency is needed for functionality `check_suggested()` prints an informative error
```r
check_suggested("ggplot22")
#> Error: 'ggplot22' must be installed for this functionality
check_suggested("ggplot2", "2.0.0")
#> Error: 'ggplot2' >= 2.0.0 must be installed for this functionality
```
This should remove the Rcpp dependency and combined with https://github.com/hadley/httr/commit/7c68198d49ea6b2abb7255c692dddb09fbeaf7b1 it should lighten the dependency load for devtools considerably.
> Move more dependencies to Suggests

- tests/testthat/test-depend.r
Test for `dev_package_deps`: https://github.com/hadley/devtools/commit/c732844d4efa93a67c5e1d96552ac479c395da5d#commitcomment-13131425
This test fails if a8728446 is reverted: https://travis-ci.org/krlmlr/devtools/builds/79799953#L6536
> Dependencies of development package include direct dependencies

- NEWS.md
- R/build.r
`build_win()`, only in interactive mode. A cheap solution to #800.
> Explicitly request consent for sending e-mail to maintainer

- R/utils.r
This PR fixes an issue where an unnecessary single space would be inserted after fields that already began with whitespace.
> don't insert unnecessary trailing whitespace (closes #940)

- R/infrastructure.R
This modifies the deprecation warning to point users to `devtools-deprecated` for help.
> Supply the 'package' argument for .Deprecated()

- R/package.r
> Fix devtools::load_all() in noninteractive mode if no DESCRIPTION exists

- R/infrastructure-git.R
- R/install-github.r
- man/install_bitbucket.Rd
- man/install_github.Rd
- man/use_github.Rd
* Correct all links re: where to get a GitHub PAT.
* Clarify scope that is needed by `devtools` ("repo") and that it's included by default in a new PAT.
* `use_github()` used to inherit `auth_token` help from `install_github()`, complete with a confusing reference to installing from a private repo. Fixed that.
~~When I re-roxygenized, I realized it was the first time for roxygen 5.0.0. 😱~~
~~I can get rid of that commit if you wish. And just re-document the things I touched with ... older oxygen?~~
> GitHub PAT link

- R/infrastructure-git.R
if you already have git in your project but don't realize it and run `use_git()`, it can be confusing to not see any output and think "why isn't it doing anything?". This isn't just a hypothetical, it happened today and it took us a few minutes to debug in @jennybc class
> use_git(): if git is already initialized, tell the user that

- R/load.r
As a continuation of #1001 you can still get lazy load errors if you use `load_all()` on a already loaded package for the same reason (promises never forced and then invalided when new code is loaded).
This was special cased for devtools so the functions would continue to work, but actually needs to be done for any package that is already loaded to avoid lazy load errors.
> Always force the promises when loading using load_all

- NEWS.md
- inst/templates/appveyor.yml
instead of polluting the logs
Follow-up to #945.
> AppVeyor template also creates Rcheck.zip as artifact

- tests/testthat/test-infrastructure.r
- tests/testthat/test-uninstall.r
This also silences them when running devtools::test()
> Test for emitted warnings

- NEWS.md
- R/deps.R
This seems to be all that is needed (assuming what is in `Additional_repositories` points to a proper 'CRAN-like' repository.
An example repository is https://github.com/rOpenGov/bibliographica, which has dependencies `gender` and `genderData` from ropensci, the rest from CRAN.
Fixes #907
> Handle repositories specified in Additional_repositories

- NEWS.md
- R/install-version.r
- tests/testthat/test-install-version.R
Fixes #943 
As far as I can tell only CRAN mirrors have a `Meta/archive.rds` file, the following all 404 (they all have valid `src/contrib/PACKAGES` though).
- http://bioconductor.org/packages/3.2/bioc/src/contrib/Meta/archive.rds
- http://packages.ropensci.org/src/contrib/Meta/archive.rds
- http://www.stats.ox.ac.uk/pub/RWin/src/contrib/Meta/archive.rds
The test fails with the current master, but succeeds with this PR.
> package_find_repos works properly with multiple repos provided

- NEWS.md
- R/revdep-summarise.R
- example: if the DESCRIPTION file in one of the checked packages is missing
> Degrade gracefully if summary cannot be retrieved for one of the checked packages

- R/deps.R
This fixes a small grammatical error in the package installation messages, such as the last line of the following:
```R
> devtools::install_github("leeper/rio")
Downloading GitHub repo leeper/rio@master
Installing rio
Installing 1 packages: BH
```
> fix message pluralization in package install

- NEWS.md
- R/deps.R
- tests/testthat/test-update.R
It was broken. Correct me please if I am mistaken.
As I see it, `NA` means that the package is not installed / available, 
and if `upgrade=FALSE` holds, then we only want to install the
ones that are not installed locally. I.e. the ones with `is.na(installed)`.
(Btw. it seems that `devtools` ignores version requirements here, but 
that is another issue.)
> Fix dependency install when not upgrading

- NEWS.md
- R/create.r
- R/infrastructure.R
- 'devtools::create()' works when supplied an empty directory,
- 'devtools::setup()' no longer 'stop()'s when a .Rproj file
already exists
> make 'create', 'setup' more flexible (closes #966)

- R/deps.R
- tests/testthat/test-remotes.r
Previously this gave the same error as other Malformed remotes, this should point users to the proper problem.
> More informative error message when a install_ function cannot be found.

- R/install-github.r
It helps to see the actual github API URL. Without this, it took me a while to find why my install_github() didn't work. It turned out to be due to the trailing space in, e.g. host="github.hostname.com/api/v3/" argument that leads to a double slashes in the final URL, e.g. "github.hostname.com/api/v3//jaimyoung/repo/zipball/master" that leads to rather uninformative error message:
client error: (403) Forbidden 
This function nicely shows "Source: https://github.hostname.com/api/v3//jaimyoung/repo/zipball/master" in the message to better reveal what went wrong.
> Show github API URL for information

- R/build.r
- tests/testthat/test-build.r
On Linux, with devtools from GitHub (050c964), the name of the built binary is incorrect.  Apparently the correct extension is "tar.gz" (not "tgz") and additional platform information is included (from the `R_PLATFORM` environment variable).
```
> (path <- devtools::build("tests/testthat/testNamespace", binary=TRUE, path=tempdir()))
'/usr/lib/R/bin/R' --no-site-file --no-environ --no-save --no-restore CMD  \
INSTALL '/home/rich/src/devtools/tests/testthat/testNamespace' --build 
* installing to library ‘/tmp/Rtmp1Sg8Nn/file135ddcab9a6’
* installing *source* package ‘testNamespace’ ...
** R
** preparing package for lazy loading
** help
No man pages found in package  ‘testNamespace’ 
*** installing help indices
** building package indices
** testing if installed package can be loaded
* …
```
> Correct name for binary packages built on Linux

- NEWS.md
- R/check-cran.r
- R/decompress.r
> revdep_check verifies integrity of already downloaded package files

- R/github.R
- R/install-bitbucket.r
- R/install-git.r
- R/install-github.r
- R/install-remote.R
- man/github_pat.Rd
- man/install_bitbucket.Rd
- man/install_git.Rd
- man/install_github.Rd
Message currently works as follows
``` r
install_github("jimhester/covr")
#> Skipping install for github remote, the SHA1 has not changed since last install.
#>   Use `force = TRUE` to force installation
```
Let me know if you want to tweak the copy or if it should only be printed interactively.
Fixes #1040
> Print message if SHA1 has not changed.

- NEWS.md
- R/check-devtools.r
- R/vignettes.r
- man/build_vignettes.Rd
Here's what it does for a package with multiple offending vignettes:
```
Running additional devtools checks for rpivotTable
Checking version number... WARNING
Version (0.1.5.7) should have exactly three components
Checking for dependencies on development versions... OK
Checking vignette titles... WARNING
placeholder 'Vignette Title' detected in 'title' field and/or
'VignetteIndexEntry' for these vignettes:
NEWS.Rmd
rpivotTableIntroduction.Rmd
```
> flag vignettes entitled "Vignette Title"; closes #960

- R/install-version.r
- tests/testthat/test-install-version.R
If the package is not available we should install only the last archived
version.
Fixes #1033
> Use the last archived version if version == NULL

- NEWS.md
- R/build.r
- R/revdep.R
When installing package during revdep check, use new libpath in addition to existing libpath. Reason: if git2r is not loaded yet, an error is raised if it not in the temporary library.
> Fix revdep_check() when git2r is not loaded

- R/infrastructure.R
> Prefer HTTPS URL

- R/deps.R
We might want to consider always changing `check_build_tools()` to not take a package and call it whenever type = 'source' on windows...
This change assumes `check_build_tools()` has been called in the past and the rtools path has been setup.
> Put Rtools on the path if needed for install_packages

- R/git.R
@stewid: Can this be done better? I have found is_commit(), but not is_branch().
> release() with detached Git head doesn't throw error

- R/rtools.r
If the R version is compiled with the new toolchain set the BINPREF
environment varaible so the proper toolchain is used for 32 and 64 bit
builds.
> Support compiling using new toolchain

- R/package-env.r
- R/shims.r
The code looking for attach looks only for `attach` as the first element in a call. Using `base::attach()` invalidates this so no NOTE is returned.
With #1138 devtools is now NOTE free, which should make future submissions a little smoother for us and CRAN.
> Fully qualify attach calls to remove NOTE

- R/has-devel.r
The comment mostly explains the reasoning and why this works. Basically checkFF calls `try(eval(e, pkg_env))` where `e` is the first argument to `.C()` and `pkg_env` is the package namespace. `dll$foo` was previously not found in the package namespace which is why the NOTE was happening. This is really a false positive so we should be able to turn it off with `dontCheck()`, but CRAN disables that when you set `--as-cran`. So the only way to remove this NOTE is to define an object in the package namespace, which is what this does.
> Remove NOTE about improper registration

- R/github.R
This will prevent most 403 errors due to rate limiting.
This PAT is from my lintr-bot account (which has access to no repositories) and has no permissions, so all it can do is read publicly available information. So it should be safe to use.
> Add a default GITHUB_PAT if running on a CI service

- NEWS.md
- R/check-devtools.r
> release() warns if NEWS.Rd exists

- R/github.R
- R/install-github.r
This takes code from `github_reponse()` to parse the GitHub response information on an error so downloading can give a more informative error message.
If the response does not contain an errors or message component the previous behavior is used.
I could not use `httr::stop_for_status()` directly at https://github.com/hadley/devtools/compare/master...jimhester:download_errors?expand=1#diff-475284c83f91b5f64ec0e4afdbd4c955R135 because the call stack would be uninformative with `sys.call(-1)`.
The following generates the following output after spamming it a bunch of times to produce an error.
```
download("test", "https://github.com/jimhester/withr/archive/1.0.1.tar.gz")
No encoding supplied: defaulting to UTF-8.
Error in download("test", …
```
> Print more detailed error message if given JSON response

- NEWS.md
- R/install.r
- R/load.r
- R/namespace-env.r
- R/unload.r
- R/zzz.r
This also finds the namespace registry once onLoad() rather than
dynamically, so the devtools DLL can be unloaded in load_all() without
needing ns_registory() when creating a new namespace.
As far as I am aware the namespace registry environment is only created once per session, so it should remain stable after it is read in .onLoad().
The main impetus for this PR was a comment by @richfitz on slack
> Having been through a bunch of pain with windows users with devtools this month, I would advise going a CRAN/drat/local cran route.  Recent devtools is enthusiastic about upgrading packages which leaves R sessions in unrecoverable positions as curl and devtools get upgraded unsuccessfully due to file locking.
Users could still have issues with prior versions of devtools, but after this newer …
> Always unload package DLLs before installation

- R/deps.R
- R/install.r
This includes packages specified in Remotes:. If build_vignettes is TRUE
they are still installed before the package.
This fixes hadley/dplyr#1809
> Install Suggested package after package installation

- R/release.r
Selecting a "no" option at the first few steps returns `NULL` which is printed to the console, unlike in later steps where `release()` returns invisibly. This PR fixes the issue.
> added return(invisible()) in release

- R/unload.r
A lot of people see this message when installing a package from Github and think there's a bug in the package being loaded and/or don't know what to do about it. This makes the message more informative and tells the user what to do if it starts acting up: restart R.
```
unloadNamespace("shiny") not successful. Forcing unload.
```
> More informative message when forcing unload

- NEWS.md
- R/compile-dll.r
The clean patterns are originally from R CMD build (https://github.com/wch/r-source/blob/4ba41332b405f29569dad311f36500391fe6f41f/src/library/tools/R/build.R#L406-L433), which @hadley referenced in the original PR (https://github.com/hadley/devtools/pull/137#discussion_r1364386)
The previous behavior was too loose, only def files with the package name should be cleaned.
The same is true for `.a` and `.dll` as well, however @wch thought there may be cases we do need to clean all of them.
Fixes https://github.com/hadley/devtools/issues/1159
cc @jeroenooms
> Only clean def files if they are 'packageName.def'

- NEWS.md
- R/run-source.r
- man/source_gist.Rd
This adds an argument `filename` to the `source_gist()` function so that a user can specify a particular file in a gist that has more than one (currently it will source the first .r file in a gist).
e.g.:
```r
source_gist("gist.github.com/ateucher/0689a1460a0ac136d3b69c371de3a57e", filename = "hi.r")
source_gist("gist.github.com/ateucher/0689a1460a0ac136d3b69c371de3a57e", filename = "hello.r")
```
> Add ability to choose a file in `source_gist()`

- R/load.r
- R/unload.r
This patch is needed to make devtools pass its own tests with the JIT enabled. The patch disables JIT compilation temporarily during loading the compiler namespace (because otherwise the JIT compilation during the loading process interferes, it loads the compiler namespace faster than devtools and locks it before devtools can insert shims into it). The patch also disables JIT (permanently) before unloading the compiler namespace - there seems to be no other way than keeping it disabled, because the call to enable it would immediately load it, which would make the unloading a waste of time. It may not be so important after all to be able to load/unload the compiler package (it should perhaps be loaded at all times anyway), but the devtools unit tests depend on this, and hence the patch.
> Disable JIT during/at compiler package loading/unloading.

- NEWS.md
- R/install-github.r
This PR modifies `install_github` to use the `tarball` endpoint rather than `zipball`.
`devtools` uses its own utility `decompress` function behind the scenes, which farms out to an appropriate decompression utility based on the file extension, so everything should just work here (and appears to in some manual testing)
> use GitHub tarball API when downloading packages

- NEWS.md
- R/github.R
> Handle case when a GitHub request returns a non-JSON error response.

- NEWS.md
- R/install-github.r
This PR reverts back to using the zipball API, to resolve https://github.com/hadley/devtools/issues/1217.
> revert change to 'tarball' API

- NEWS.md
- R/utils.r
Fixes 'nchar(text) : invalid multibyte string' Errors
> Set DESCRIPTION encoding if it is declared

- R/git.R
- R/install-remote.R
- tests/testthat/test-remotes.r
packageDescription() loads the description from the namespace if it is
already loaded, which is not what we want for e.g. revdep_check().
This forces the lookup to be on the current .libPaths() only.
The ceiling parameter in gitr2::discover_repository() is used so that
use_git() only returns true if the input path is the base of the git
repository. This prevents test packages from being considered to be
using git.
> Fixes to ensure package2remote respects an updated .libPath()

- NEWS.md
- R/download-method.R
An option for keeping description correct WRT `install_github()`, especially on R 3.1.
An alternative for those users is:
```R
options(download.file.method = "curl")
```
> solution for #1244

- DESCRIPTION
- NEWS.md
- R/test.r
requires testthat >= 1.0.3 (hadley/testthat#505).
> Don't load test helpers twice in test()

- appveyor.yml
by manually installing curl. (No idea why it isn' picked up.)
> Fix AppVeyor tests

- inst/templates/appveyor.yml
Seems to work well, e.g., https://ci.appveyor.com/project/krlmlr/r-appveyor/build/1.0.1125/job/jko81yk3uu3blhgc#L12
Reference: https://github.com/krlmlr/r-appveyor/issues/31#issuecomment-203390516
NEWS entry:
```
* Caching is enabled by default in the AppVeyor template created by
`use_appveyor()` (#1290, @krlmlr).
```
> Add cache setting to AppVeyor template

- NEWS.md
- R/deps.R
- tests/testthat/test-install.R
e.g. in `devtools::install(dependencies = FALSE)`
With test.
NEWS entry:
```
* Package installation doesn't query `available_packages()` unless needed, this
speeds up installation in some scenarios (#1269, @krlmlr).
```
> Avoid unnecessary query of available_packages()

- R/check-cran.r
- R/revdep.R
Follow-up to #1366.
@jcheng5: Can you please try:
```r
devtools::install_github("hadley/devtools#1368")
```
@hadley: I broke revdep check, this PR fixes it.
> Don't pass skip to check_cran()

- README.md
Avoid rendering backtick literals by preserving list indentation
**before**
**after**
> Small markdown formatting fix

- NEWS.md
- R/cran.r
- R/deps.R
- R/install.r
- man/install_cran.Rd
- man/install_deps.Rd
- man/package_deps.Rd
- man/update_packages.Rd
This PR addresses https://github.com/hadley/devtools/issues/1243.
There were two issues, first the prior behavior of forcing `type = binary` was causing drat repositories without binary packages to fail, second the `repos` argument was not being passed onto `update()`.
With these changes the following correctly installs `rrdf` and `rrdflibs` as expected by @cboettig.
``` r
devtools::install_github("ropensci/RNeXML", dep=TRUE, repos = c("https://cran.rstudio.com", "http://packages.ropensci.org"))
```
> These changes address uses non-standard CRAN like repositories e.g. (drat)

- DESCRIPTION
- R/check.r
- R/install.r
New callr uses processx, so don't need to quote
paths any more. (It is actually a bug to quote
them.)
This also requires pinning pkgbuild to HEAD,
unfortunately. This should be temporary.
> No shQuote for new pkgbuild/callr

- R/check.r
- man/check.Rd
This adds back the check_dir argument, although it is now ignored. The RStudio IDE calls `devtools::check()` with this argument, which caused #1592.
The `check_dir` argument was originally added for #337, however rcmdcheck does support the `--output` argument to `R CMD check`, so you can specify the check directory by passing `args = "--output=/foo/bar"` (as I mentioned in the help for `check_dir`.
Alternatively we could modify `rcmdcheck()` to take a `check_dir` argument or add the `args = "--output"` if `check_dir` is not `NULL`. Not sure what the best approach is.
> Add check_dir argument for backwards compatibility

- R/infrastructure-git.R
- R/infrastructure.R
- R/utils.r
- tests/testthat/helper-github.R
- tests/testthat/test-github-connections.R
Would like suggestions on the warning message.
https://github.com/hadley/devtools/compare/master...jimhester:github-connection-tests?expand=1#diff-475284c83f91b5f64ec0e4afdbd4c955R191
> Fix the test failures / errors and add a warning for pkg arguments that are not `.`.

- R/check-win.r
Otherwise we get:
```
check_win_release()
#> Error in pkg$package : $ operator is invalid for atomic vectors 
```
> Reinstate package coercion in check_win family

- NEWS.md
- R/decompress.r
Whenever R is compiled with no 'unzip' package installed in the underlying operation system, the getOption( 'unzip' ) variable is set to an empty string. (At least for R-3.4.0 on a vanilla Ubuntu16.04
Since the empty string doesn't trigger the if clause and its usage of the R interal utils::unzip function, I added another exception.
> [my_unzip] add exception

- R/check-win.r
Also the convention in the tidyverse is to soft-deprecate before deprecating for at least one minor release cycle (i.e. middle number). Should we follow the same convention in r-lib? cc @hadley
> Fix build_win() alias to check_win()

- NEWS.md
- R/install-version.r
Because of the impending API change in the package git2r, I want to write documentation that advises users to install version 0.21.0 of git2r, which is still the current version of CRAN. This doesn't work with the current version of `devtools::install_version` on Windows or macOS. This PR fixes it.
I read about the [diaspora](https://github.com/r-lib/devtools#diaspora). However, I still decided to send the PR here because unlike packages like pkgbuild and usethis, remotes is not yet a dependency for devtools. Also, `remotes::install_version` doesn't have this issue. Please feel free to close it.
**Edit:** I investigated more. The implementation of `remotes::install_version` has substantially changed from the one in devtools, i.e. it doesn't use `install.packages` to determine the download …
> Enable install_version to install current version of package on Windows/macOS

- DESCRIPTION
foghorn 1.0.1 was just accepted on CRAN, and is now compatible with R >= 3.1
> update minimum foghorn version to ensure compatibility with R >= 3.1

- DESCRIPTION
The current version with the S3 methods is [0.21.0.9002](https://github.com/ropensci/git2r/blob/d17df22adeba0340d9d198b03809c571765df6d2/DESCRIPTION#L7).
This is a tiny PR, so I don't think this requires any mention in the NEWS. Please let me know if you feel otherwise.
> Require git2r >= 0.21.0.9002.

- R/check-win.r
in `check_win()`.
Are there other occasions where we want to show the version?
> Be explicit about the version checked

- R/run-source.r
I think they're similar that the reader of one function might benefit from being aware of the other.
> `source_gist()` and `source_url()` reference each other

- NEWS.md
- R/install-gitlab.r
- man/gitlab_pat.Rd
- man/install_gitlab.Rd
'github' entries changed to 'gitlab' in the file `install-gitlab.R` and documentation
> Typos fixed in install-gitlab.R file

- NEWS.md
- R/reload.r
Historically `reload()` only reloaded attached packages, this changes
the behavior to reload packages which are only loaded, not attached as
well.
@wch, @hadley Do either of you remember if there was a reason `reload()` only reloaded attached packages? It seems to me like it should reload loaded, but not attached packages as well.
> Reload loaded packages as well as attached packages

- R/check.R
Instead of using the `--output` argument of `R CMD check`.
`--output` is impossible to quote correctly on windows,
because of the processx auto-quoting and/or R's
command line reparsing.
Closes #1864.
> check: pass check_dir to rcmdcheck

- R/install.R
Not sure if I need to make an issue first, but the upgrade argument isn't being passed through to install_deps.
If there's guidance on writing a test I can do that as well
> Passed upgrade through to install_deps

- R/release.R
This allows reviewing the `.tar.gz` before even sending it to CRAN.
> Build before confirming submission

- R/zzz.R
If the lib path has changed since loading usethis,
.onAttach potentially fails when it tries to attach
usethis as the new lib path might contain a different
usethis version.
Closes #1987.
> Fix attaching usethis if lib path has changed

- R/package.R
This ensures that `as.package()` returns the proper text on Windows.
> Always parse package DESCRIPTION as UTF-8, fixes #1948

- R/check-git.R
Closes #2064
Looks like this:
```
── Running Git checks for devtools ─────────────────────────────────────────────────
Current branch: release-report-branch 
Checking uncommitted files... OK
Checking synchronisation with remote branch... OK
────────────────────────────────────────────────────────────────────────────────────
Were Git checks successful?
1: I forget
2: Uhhhh... Maybe?
3: Of course
Selection: 
```
> Report current branch in release()'s git checks

- R/document.R
To avoid crashing due to (presumably) the external pointers pointing to memory that has been reclaimed
(I didn't add a news entry since the only person this really affects is me)
> Special case document() when applied to roxygen2 itself

- NEWS.md
- R/check-win.R
Fixing #2152 As per https://github.com/r-lib/devtools/issues/2152#issuecomment-559144986, by adding `add = TRUE` on the `on.exit/on.error` collector.
> Added add = TRUE For `check_win`

- R/install.R
- man/install.Rd
It was renamed in https://github.com/r-lib/devtools/commit/c28507106b864ac724bb1d5551dd6066f186daf4#diff-b4729bd8d077a10ed051487dfd8e39ea
> Update build_vignettes doc to follow renaming local -> build

- inst/rstudio/addins.dcf
Rstudio can be used to document a package with a keyboard shortcut (CTRL/CMD+ALT+D) and a few settings under Project Options -> Build Tools -> Generate documentation with Roxygen. Unfortunately it is not possible to get it to run `devtools::document()` without any arguments which is useful as it uses the settings (roclets) given in the `DESCRIPTION` file as desired when using `roxygen2` extensions as e.g. https://github.com/mikldk/roxytest.
One solution would be to get this functionality directly in Rstudio, but that seems to be difficult: https://github.com/rstudio/rstudio/issues/5201. 
This simple addin would be a simple way to achieve the same.
> Adding addin for document().

- NEWS.md
- R/install.R
- man/install_deps.Rd
- tests/testthat/test-install.R
> install_dev_deps() passes formal args onto install_deps()

- inst/rstudio/addins.dcf
None of the other `Name`s have a full stop at the end.
> Fix typo in addins.dcf

- NEWS.md
- R/build-readme.R
- R/install.R
- tests/testthat/test-build-readme.R
Also needed to make some changes to `install()` so that it doesn't actually reload when `reload = FALSE`
Code coverage is high because of an existing test.
> Generalise build_readme() to build_rmd()

- R/test.R
to remove version check that is already ensured by `DESCRIPTION`.
> Clean up test()

- DESCRIPTION
the latest update to foghorn ensures that the results reported during `release()` are accurate.
> increase version number for foghorn dependency

- R/build-manual.R
- R/build-readme.R
- R/install.R
- R/run-examples.R
- R/vignettes.R
To make sure that they are interleaved correctly.
Fixes https://github.com/r-lib/callr/issues/154
> Redirect callr stderr to stdout

- NEWS.md
- R/check.R
- tests/testthat/test-check.R
> Only document in check if roxygen2 versions match

- NEWS.md
- R/check-win.R
Need another add = TRUE for `on.exit` on line https://github.com/r-lib/devtools/blob/master/R/check-win.R#L129, otherwise  it resets all the renaming/replacing that is above.
> Need another add = TRUE for on.exit on upload ftp for #2157 fix again

- R/test.R
So extra with_dir not necessary? Not sure what assumptions covr is making, but this made it work again for me.
> test_files includes full path

- R/pkgbuild.R
- man/build.Rd
This simple change fixes the problem in issue #2295 by changing the default to `manual = TRUE`.  The manual is only included when necessary, because `pkgbuild::build` just calls `R CMD build`, which makes the inclusion decision.
> Build manual

- NEWS.md
- R/check-win.R
- tests/testthat/test-check.R
- tests/testthat/testTest/DESCRIPTION
Earlier, I was running `check_win_release(email = 'myname@domain.dk')` on a package I am working on. Due to us using both Authors@R and the Maintainer field in our DESCRIPTION file, the report was sent to a different email address. Luckily it was someone I know and it is no problem.
It is bad form to send the reports to unsuspecting people, so I wrote a check for the `change_maintainer_email()` function such that this does not happen again. 
This issue has come up before in #2073 and I suspect that we are not the only people who have errouneously used both authors@R and Maintainer field.
I wrote a unit test for the change, and had to change a DESCRIPTION file or include a new package. I chose to change the testTest package's description file to use both Authors@R and Maintainer. This had …
> Check that the email is actually changed in change_maintainer_email()

- .gitignore
- NEWS.md
- R/vignette-r.R
- R/vignettes.R
- tests/testthat/test-vignettes.R
This PR changes the `.gitignore` entries created by `build_vignettes`, from `doc` and `Meta` to `/doc/` and `/Meta/`, to prevent matching nested folders, as per the discussion in the linked issue.
Implements #2317.
> Let `build_vignettes` create more specific .gitignore entries

- .Rbuildignore
- DESCRIPTION
- LICENSE
- LICENSE.md
- man/devtools.Rd
And remove R Core from authors list since all GPL code from R itself has been removed/rewritten.
Fixes #2326
> Re-license as MIT

- R/dev-mode.R
Please forgive me if I missed something here; this is my first time
contributing to an R package.
The dev_mode call to `dir_ls` appears to be incorrect, in that it uses
the argument `type = 'folder'`.   I do not know whether this was valid
at some point in the history of `fs::dir_ls`, but it is invalid now:
```
> fs::dir_ls('.', type = 'folder')
Error in match.arg(type, names(directory_entry_types), several.ok = TRUE) :
'arg' should be one of “any”, “unknown”, “file”, “directory”, “symlink”, “FIFO”, “socket”, “character_device”, “block_device”
> fs::dir_ls('.', type = 'directory')
R           inst        man         man-roxygen pkgdown     revdep
tests       vignettes
```
I hit this bug by a route I now find difficult to reconstruct, but the
relevant error is in: …
> Fix 'folder' argument to `dir_ls`

- NEWS.md
- R/create.R
- man/create.Rd
This PR disables `open` by default to avoid the duplicate sessions opened in the RStudio package creation gui
Closes #2346
> Don't open projects with `create()`

- NEWS.md
- R/active.R
- inst/rstudio/addins.dcf
I prefer the user experience this offers. I feel better oriented and informed about what command I actually invoked and how things are going.
And even, morally, it seems fitting to use `Interactive: true` for these:
https://rstudio.github.io/rstudioaddins/#execution-modes
> The `Interactive` field within the addin registration describes whether the addin is interactive or non-interactive. It’s important to understand when an addin should be declared as interactive versus non-interactive, as this effects how RStudio will attempt to execute the addin:
>
> * Interactive addins are invoked by emitting a call to their function directly into the R console. For addins that display user-interface (e.g. using a Shiny application) this enables users to stop/interrupt them.
>
> * Non-interactive …
> Execute the addins in interactive mode

- NEWS.md
- inst/rstudio/addins.dcf
Implementing idea suggested in #2358: An Rstudio addin to run all examples.
> New addin for run_examples()

- R/test.R
- R/usethis.R
This is related/follow up to https://github.com/rstudio/rstudio/pull/10254
Trying to be mode useful when `devtools::test()` is called from the ide (non interactive) and the testing infratructure is not setup. So that we'd get: 
instead of: 
I'm not sure this would need to distinguish between Rstudio ide and other non interactive contexts. 
Perhaps this could be followed up later from the perspective of the ide with ui dialogs that mimic the experience of running `devtools::test()` interactively.
> `devtools::test()` case when not `interactive()` and testing infrastructure not found

- R/uninstall.R
- man/uninstall.Rd
Documentation for `uninstall()` references the `remove.package()` function, which should be `remove.packages()`.
> Fix typo in documentation

- NEWS.md
- R/sitrep.R
- tests/testthat/_snaps/sitrep.md
- tests/testthat/test-sitrep.R
Closes #2397
As per @jgutman advice:
* Use the long version number for RStudio, when available. Fall back to shorter version otherwise.
* URL encode the version number.
* Add `manual=true` to the URL we use when checking for updates.
Also makes this helper much less likely to throw an error, even if it does not succeed.
> Adjust to new RStudio version numbering

- NEWS.md
- R/test.R
Currently I'm seeing:
```
> devtools::test('~/Sync/Projects/R/r-lib/rlang')
ℹ Loading rlang.
ℹ Testing rlang
ℹ Loading rlang.
```
With this PR this becomes:
```
> devtools::test('~/Sync/Projects/R/r-lib/rlang')
ℹ Testing rlang.
ℹ Loading rlang.
```
> Fix redundant `load_all()` call in `devtools::test()`

- NEWS.md
- R/check.R
- man/check.Rd
Related to #2448 and https://github.com/r-lib/rcmdcheck/pull/185
I think devtools should do less: just accept the behaviour and docs around `check_dir` from rcmdcheck.
> Use same default as rcmdcheck itself

- NEWS.md
- R/check.R
- man/check.Rd
Closes #2459 (for R >= 4.2), which seems like a improvement worth having
~Logically, this seems like it should close #2459 and yet I don't think it does? My local R version is not ideal for this at the moment, so I'm going to come back to this when I can experiment with it more easily.~ *I'm on R 4.2 and yes this does what we want.*
> Surface unused imports with `check(cran = TRUE)`

- DESCRIPTION
- NEWS.md
- R/dev-mode.R
- R/devtools-package.R
- _pkgdown.yml
- man/dev_mode.Rd
- man/devtools-package.Rd
As indicated in #2467, `dev_mode()` is no longer recommended or receiving fixes.  This PR provides documentation so that users know to migrate away from using it.
> Deprecate dev_mode()

- DESCRIPTION
- NEWS.md
- R/active.R
- R/test.R
- tests/testthat/test-active.R
This was never used correctly because we're passing the path to the package root, instead of the test directory. Additionally, based on https://github.com/hadley/testcoverage, they don't actually appear to be needed.
Fixes r-lib/testthat#1858
---
@jennybc my main scepticism here for the case of `test_coverage_active_file()`, I can't see how this can possibly work (even though it does). As far as I can tell, nothing in `test_coverage_active_file()` causes either `TESTTHAT_PKG` or the edition to be set correctly, but the tests still pass. 
...
Ooooh maybe the problem is that `test_coverage_active_file()` never actually reveals when the test fails.
...
Yes, that was the problem, and once I fixed that, it revealed that the snapshot paths weren't set up correctly, and it helped me understand …
> Improve test coverage functionality

- .lintr
- R/check.R
- man/check.Rd
> Don't inherit `error_on` docs from rcmdcheck

- README.md
The cover image wasn't showing in the `Learning More` section of the ReadMe:
This should fix it:
> Update cover image in README.md

- R/run-examples.R
Fixes #2559 because you do not need testthat helper when running examples!
> Do not load test helper with `run_examples()`

- R/check-mac.R
Adds a missing "for" in the sentence about checking results in 5-10 min.
> Fix small typo in check-mac.R

- NEWS.md
- R/check-mac.R
- R/release.R
- R/run-source.R
> Use httr conditionally

- R/check.R
- man/check.Rd
Note: the sentence is 3 characters over 80, but it was already 1 character over initially, so I didn't wrap.
> Fix typo with backticks in `check(vignette)` argument

- DESCRIPTION
- NEWS.md
- R/install.R
- R/utils.R
- man/install.Rd
This dSYM file contains the file/line information that allows debuggers to figure out the source location.
As noted in the argument doc, generating this file is only one half of the battle. Because the package is built from a temporary location, the source info points to dangling paths. It is possible to remap these paths from lldb though.
> Generate dSYM file in `install()` on macOS

- NEWS.md
- R/install.R
- man/install.Rd
- man/install_deps.Rd
Follow up for https://github.com/r-lib/devtools/pull/2598
It's not necessary to generate a dSYM file if you use `build = FALSE`.
The problem with `build = TRUE` is that if you're not generating dSYM files, the linker inserts paths to object files that contain the DWARF debug info and these paths are pointing to dangling temporary locations:
```
> nm -a /Users/lionel/R/Library/4.4-aarch64/rlang/libs/rlang.so | grep OSO
0000000067ef7d43 - 00 0001   OSO /private/tmp/RtmpIM0xjp/R.INSTALLe9c020cfb3cd/rlang/src/capture.o
0000000067ef7d43 - 00 0001   OSO /private/tmp/RtmpIM0xjp/R.INSTALLe9c020cfb3cd/rlang/src/internal.o
0000000067ef7d43 - 00 0001   OSO /private/tmp/RtmpIM0xjp/R.INSTALLe9c020cfb3cd/rlang/src/rlang.o
0000000067ef7d43 - 00 0001   OSO …
```
> Remove `generate_dsym` argument
