R/install-git.r, man/install_git.Rd
a new typo had been introduced. now it should be fine
=> fix the fix for #685

R/install.r, R/vignettes.r, tests/testthat/test-load-hooks.r
(I don't know a sane way to test this, which may make it futile?)
=> Clean up some partial matches.

R/install-github.r, tests/testthat/test-github.r
Testing with hadley/devtools as known submodule-free and armstrtw/rzmq
as known submodule-using.
Implements and tests suggestion in  #776
=> Slight refactor submodule warning to add tests

R/doctor.R, R/git.R, R/infrastructure-git.R, R/install-github.r, man/install_github.Rd, man/use_github.Rd
Very trivial fix. There is no functional changes.
=> [FIX]correct name for GitHub

R/deps.R, R/revdep.R
nothing terribly important here, just trying to polish
=> minor doc typos

R/doctor.R
introduced in #830: https://travis-ci.org/hadley/devtools/builds/64963102#L1720
=> work around bogus NOTE

R/load.r
=> Satisfy R CMD check for new package

README.md
Changing CRAN address; I understand that https is the thing now.
=> small potential update: README.md -> .RProfile

R/install.r
=> Fix typo in documentaton

R/infrastructure.R
This seems to be necessary: https://github.com/yihui/knitr/blob/f38d038561938145fb084c6370ab09b291a87025/man/vignette_engines.Rd#L12-L14
=> Also suggest rmarkdown package when creating vignette

man/check.Rd
Fixes WARNING about inconsistent documentation.
=> Re-oxygenate

.Rbuildignore, README.md, appveyor.yml, tests/testthat/test-vignettes.r
Set up and forget, essentially saves you from running `build_win()`. Please sign up at https://ci.appveyor.com and register devtools. Should test all commits and pull requests.
Build results: https://ci.appveyor.com/project/krlmlr/devtools (because this branch doesn't contain #910 yet).
=> Test also with r-appveyor

R/infrastructure.R, README.md
- `use_appveyor()`
- `README.md`
=> Use SVG badges for AppVeyor

R/test.r
=> don't depend on testthat if testing testthat itself

R/deps.R, man/install_deps.Rd, man/package_deps.Rd, man/update_packages.Rd
Fills in some of the holes in documentation on the `package_deps()` function.
=> update 'package_deps' documentation

README.md
List-ify to make it easier to skim through available options.
=> Tweak install_* section of README

appveyor.yml
- in case of failure, save check directory as artifact
Per @HenrikBengtsson's suggestion in krlmlr/r-appveyor#37.
=> Unclutter AppVeyor output

NEWS.md, R/revdep.R
I was missing that information in the output.
=> Be more verbose about which package is installed for revdep check

tests/testthat/test-remotes.r
=> Remove trailing /

R/doctor.R
=> Find the package root for dr_github()

R/build-dependencies.R, R/build.r
Part of #1087, if check() does its own checking.
=> refactor: add verbose arg to has_latex

CONTRIBUTING.md
=> Repeated word `like like` on CONTRIBUTING.md

inst/templates/README.Rmd, tests/testthat/infrastructure/README.Rmd
I made a related PR to the R Packages book then realized this needed to happen to make it true!
https://github.com/hadley/r-pkgs/pull/345
=> Use github_document format in README.Rmd

NEWS.md, R/load-code.r
=> load_code loads files from R/unix and R/windows, closes #1102

NEWS.md, inst/templates/revdep.R
=> Update revdep template

NEWS.md, R/check.r, man/check.Rd
=> New arg 'manual = FALSE' to check()

CONTRIBUTING.md
hand -> happy as suggested by @jennybc
=> typo in CONTRIBUTING.md

R/release.r
Correct typo on line 70 so that it reads "Building and checking".
=> Correct typo in release.r

NEWS.md, R/install-github.r, man/install_github.Rd
=> Fully specify host url for install_github

NEWS.md, R/check-cran.r, R/deps.R, R/download-method.R, R/release.r
Fixes #1059 
cc @jimhester, @bbolker 
@jjallaire Can you please confirm that it's ok for me to re-license RStudio source in this way?
=> Pick https mirror if possible.

R/install-github.r
=> Specify a protocol if one is not provided.

NEWS.md, R/rtools.r
Fixes https://github.com/hadley/devtools/issues/717#issuecomment-225370029 and the appveyor errors
https://ci.appveyor.com/project/hadley/devtools/build/1.0.600#L193
=> Updates for Rtools34

R/package-deps.r
This should resolve Issue #1247 
(I hereby make zero claim on copyright on this simple patch)
=> BUG FIX: parse_deps() did not handle spaces after version specification

appveyor.yml
this should fix the AppVeyor build error (I just had the same problem a couple of days ago and ended up here because of an unrelated bug, so decided to submit this since it's a very easy fix)
=> add USE_RTOOLS: true to appveyor.yml

inst/templates/omni-README
=> It's username/repo, not repo/username

NEWS.md, R/check-cran.r, R/deps.R, R/utils.r, man/package_deps.Rd
And install it if the user requests to do so.
=> Check and install bioconductor

R/session-info.r, tests/testthat/test-session-info.R
Will now error with a more informative error message than previous (https://travis-ci.org/hadley/r4ds/builds/148333172#L4144)
=> Handle case of uninstalled package being passed to session_info

DESCRIPTION
=> Change git2r minimum version to 0.12.1

DESCRIPTION, R/document.r, R/install.r, R/missing-s3.r, R/release.r, R/reload.r, R/run-examples.r, R/test.r, R/uninstall.r, R/utils.r, tests/testthat/test-remote-metadata.R
I am opening this as a PR as an additional check that I have gotten everything right, but it should work, then can merge both PRs.
=> Changes to work with the desc PR of pkgload

NEWS.md, R/document.r
=> No longer run test helpers in document()

DESCRIPTION, NEWS.md, R/check.r, man/check.Rd, man/load_all.Rd
Fixes https://github.com/rstudio/rstudio/issues/2235
=> Add an error_on argument to check and check_built

NEWS.md, R/install-remote.R
So they are not reinstalled by install_deps()
=> Correctly detect RemoteSha of packages installed locally

R/release.r
Original docs say that the package is released with FTP when in fact it's now down with a POST request to an HTTP endpoint. 
Also found a stray line that wasn't doing anything.
=> Housekeeping edits to release.r

README.md
I made a fair amount of changes, mainly following the structure of the ggplot2 readme.
Comments and additional suggestions on things which should go in would be great!
You should be able to view the rendered md with the View button, as I know the diff is kind of hard to read :)
=> Rework the readme

.github/lock.yml
* Add lockbot to lock old issues <https://probot.github.io/apps/lock/>
=> Add lockbot 🔒🤖

NEWS.md, R/r-hub.R, man/check_rhub.Rd
=> Forwarding arguments to rhub::check() from check_rhub()

R/remotes.R, man/remote-reexports.Rd
Links in remote-reexports.Rd now to `remotes::install_*`
=> Fixes #2136

vignettes/dependencies.Rmd
Closes #2142
This has come up a few times before. Maybe this will help.
=> Point out that Remotes doesn't eliminate need to declare a dependency

NEWS.md, R/spell-check.R
=> Suggest installing spelling when using spell_check

R/document.R
Now that we require recent roxygen2
=> Simplify document()

R/release.R
This is the only question you need to routinely answer no to and I find it super annoying
=> Remove prompt to open package

R/check-win.R
Since it's important to notice
=> Embolden email in check_win()

R/sitrep.R
=> Make sitrep bullets consistent

DESCRIPTION, R/build-readme.R
Closes #2364 
I recently tried to build a non-existent file and would have preferred to learn this *before* installing the package.
I looked around re: error messages and did my best re: what I report and how I style it.
=> Check for file existence and check early

R/check.R, man/check.Rd
Something minor I found while reading the docs.
=> Fixed typo

R/check-doc.R, man/check_man.Rd
The Value section was missing a line of the roxygen2 comment in check_man.Rd
=> technical edit; added missing single quote character

R/check.R
Works best in conjunction with https://github.com/r-lib/pkgbuild/pull/139
=> Mildly improve visual hierarchy of devtools::check()

.github/workflows/lint.yaml, .lintr, R/test.R
=> Add linting action

NEWS.md, R/install.R
=> Unregister package before installing instead of unloading

DESCRIPTION, NEWS.md, R/test.R, tests/testthat/test-test.R
=> Set package in `test_active_file()`

README.md
Addresses issue #2563
Updated the readme to reflect the completion of the 2nd edition and the online availability of the 1st edition to avoid confusion.
Also updates the reference to Posit Community.
=> update statements re. pkgs book, update url
